
class HadithText{
  final List<String> fetchedHadiths = [
    "The best among you are those who have the best manners and character. - Prophet Muhammad (PBUH)",
    "Actions are judged by intentions. - Prophet Muhammad (PBUH)",
    "The seeking of knowledge is obligatory for every Muslim. - Prophet Muhammad (PBUH)",
    "None of you truly believes until he loves for his brother what he loves for himself. - Prophet Muhammad (PBUH)",
    "The most beloved people to Allah are those who bring the most benefit to others. - Prophet Muhammad (PBUH)",
    "A Muslim is one from whom people are safe from his tongue and hand. - Prophet Muhammad (PBUH)",
    "The strong believer is better and more beloved to Allah than the weak believer, while there is good in both. - Prophet Muhammad (PBUH)",
    "He who does not show mercy to our young and does not honor our elders is not one of us. - Prophet Muhammad (PBUH)",
    "Whoever removes a hardship from a believer, Allah will remove one of his hardships on the Day of Judgment. - Prophet Muhammad (PBUH)",
    "The best of people are those who are most beneficial to others. - Prophet Muhammad (PBUH)",
    "Do not envy one another, do not hate one another, and do not turn away from one another. - Prophet Muhammad (PBUH)",
    "The best of deeds is to bring happiness to a believer. - Prophet Muhammad (PBUH)",
    "Be in this world as though you were a stranger or a traveler. - Prophet Muhammad (PBUH)",
    "The best gift to a child is a good education. - Prophet Muhammad (PBUH)",
    "He who has an atom's weight of arrogance in his heart will not enter Paradise. - Prophet Muhammad (PBUH)",
    "The one who does not keep his trust has no faith. - Prophet Muhammad (PBUH)",
    "Feed the hungry, visit the sick, and free the captive. - Prophet Muhammad (PBUH)",
    "A believer is like a bee that eats what is good and produces what is good. - Prophet Muhammad (PBUH)",
    "The most perfect believer in faith is the one who is best in conduct. - Prophet Muhammad (PBUH)",
    "Seek knowledge from the cradle to the grave. - Prophet Muhammad (PBUH)",
    "It is enough of a sin for a man to hold his brother in contempt. - Prophet Muhammad (PBUH)",
    "He who is not thankful for small things will not be thankful for large things. - Prophet Muhammad (PBUH)",
    "Charity does not decrease wealth. - Prophet Muhammad (PBUH)",
    "Whoever believes in Allah and the Last Day should speak good or remain silent. - Prophet Muhammad (PBUH)",
    "The prayer of a Muslim for his brother in his absence is answered. - Prophet Muhammad (PBUH)",
    "The person who severs ties with his relatives will not enter Paradise. - Prophet Muhammad (PBUH)",
    "Beware of suspicion, for suspicion is the greatest falsehood. - Prophet Muhammad (PBUH)",
    "A smile is charity. - Prophet Muhammad (PBUH)",
    "The best of you are those who are best to their families. - Prophet Muhammad (PBUH)",
    "Islam is built upon five pillars. - Prophet Muhammad (PBUH)",
    "He who wishes to enter Paradise through its best door must please his parents. - Prophet Muhammad (PBUH)",
    "The best among you are those who have the best manners. - Prophet Muhammad (PBUH)",
    "Sincerity is the foundation of faith. - Prophet Muhammad (PBUH)",
    "Do not harm yourself or others. - Prophet Muhammad (PBUH)",
    "The one who guides to something good has a reward similar to that of its doer. - Prophet Muhammad (PBUH)",
    "Beware of minor sins, for they will accumulate and destroy a person. - Prophet Muhammad (PBUH)",
    "He who does not show mercy to our young is not one of us. - Prophet Muhammad (PBUH)",
    "Whoever intends to do a good deed but does not do it, Allah records it as a complete good deed. - Prophet Muhammad (PBUH)",
    "The most merciful of people to others will be the most merciful of them to himself. - Prophet Muhammad (PBUH)",
    "Your smile for your brother is an act of charity. - Prophet Muhammad (PBUH)",
    "He who does not have mercy on people, Allah will not have mercy on him. - Prophet Muhammad (PBUH)",
    "The best of the deeds is to bring happiness to the believer. - Prophet Muhammad (PBUH)",
    "Whoever fulfills the needs of his brother, Allah will fulfill his needs. - Prophet Muhammad (PBUH)",
    "The greatest of richness is the richness of the soul. - Prophet Muhammad (PBUH)",
    "He who does not repent is like a person who has no sin. - Prophet Muhammad (PBUH)",
    "There are two blessings that many people lose: health and free time. - Prophet Muhammad (PBUH)",
    "The person who is best to his wife is the one who is best to her. - Prophet Muhammad (PBUH)",
    "O Allah, help me to remember You, to be grateful to You, and to worship You in the best manner. - Prophet Muhammad (PBUH)",
    "The one who has the most evil is the one who is rejected by others. - Prophet Muhammad (PBUH)",
    "Beware of the fire, even if it is by giving half a date in charity. - Prophet Muhammad (PBUH)",
    "The best way to seek knowledge is to ask questions. - Prophet Muhammad (PBUH)",
    "He who does not honor the elders is not one of us. - Prophet Muhammad (PBUH)",
    "The one who is grateful will be given more. - Prophet Muhammad (PBUH)",
    "The best form of remembrance is to say, 'La ilaha illallah' (There is no god but Allah). - Prophet Muhammad (PBUH)",
    "The person who guides others towards goodness is rewarded. - Prophet Muhammad (PBUH)",
    "Your faith is not complete until you love for your brother what you love for yourself. - Prophet Muhammad (PBUH)",
    "He who does good deeds, even if small, will have them multiplied. - Prophet Muhammad (PBUH)",
    "The best of you are those who have the best manners and character. - Prophet Muhammad (PBUH)",
    "Good character is the key to Paradise. - Prophet Muhammad (PBUH)",
    "Whoever believes in Allah and the Last Day should speak good or remain silent. - Prophet Muhammad (PBUH)",
    "The best of people is the one who is most beneficial to people. - Prophet Muhammad (PBUH)",
    "Treat others as you wish to be treated. - Prophet Muhammad (PBUH)",
    "A person is upon the religion of his friend, so let one of you look at whom he befriends. - Prophet Muhammad (PBUH)",
    "He who possesses the following three qualities is a hypocrite: When he speaks, he lies; when he makes a promise, he breaks it; and when he is trusted, he betrays. - Prophet Muhammad (PBUH)",
    "The one who is not content with what Allah has given him is like one who does not believe in Allah. - Prophet Muhammad (PBUH)",
    "Whoever seeks knowledge and does not do good with it will have a thorny path. - Prophet Muhammad (PBUH)",
    "He who strives to provide for his family is like a warrior in the path of Allah. - Prophet Muhammad (PBUH)",
    "The one who shows you your faults is your friend. - Prophet Muhammad (PBUH)",
    "It is better to be a servant than to be arrogant. - Prophet Muhammad (PBUH)",
    "The one who does not give the due rights of others is not a believer. - Prophet Muhammad (PBUH)",
    "When a man dies, all his deeds are cut off except for three: ongoing charity, beneficial knowledge, or a righteous child who prays for him. - Prophet Muhammad (PBUH)",
    "The best of you are those who are best in character. - Prophet Muhammad (PBUH)",
    "The one who stands up for justice is the best of men. - Prophet Muhammad (PBUH)",
    "He who does not fulfill his promises has no faith. - Prophet Muhammad (PBUH)",
    "A believer is not one who eats his fill while his neighbor is hungry. - Prophet Muhammad (PBUH)",
    "The best among you are those who have the best manners and character. - Prophet Muhammad (PBUH)",
    "The one who has the most complete faith is the one who has the best character. - Prophet Muhammad (PBUH)",
    "He who guides to good is like the one who does it. - Prophet Muhammad (PBUH)",
    "Keep your tongue wet with the remembrance of Allah. - Prophet Muhammad (PBUH)",
    "The most beloved of deeds to Allah are those which are done consistently, even if they are few. - Prophet Muhammad (PBUH)",
    "He who seeks to know Allah will find him through knowledge. - Prophet Muhammad (PBUH)",
    "The one who is not merciful to others will not receive mercy. - Prophet Muhammad (PBUH)",
    "He who has the best character will be closest to me on the Day of Resurrection. - Prophet Muhammad (PBUH)",
    "The best of deeds is to pray on time. - Prophet Muhammad (PBUH)",
    "Take advantage of five before five: your youth before your old age, your health before your sickness, your wealth before your poverty, your free time before your busy time, and your life before your death. - Prophet Muhammad (PBUH)",
    "The best of companions is the one who helps you to remember Allah. - Prophet Muhammad (PBUH)",
    "No one will enter Paradise except through the mercy of Allah. - Prophet Muhammad (PBUH)",
  ];
}